# checkinpurple Setup Script - Supabase & Agora

echo "🎵 checkinpurple Production Setup"
#!/bin/bash
# SoundSync Setup Script - Supabase & Agora

echo "🎵 SoundSync Production Setup"
echo "================================"
echo ""
echo "This script will help you configure Supabase and Agora credentials"
echo ""
echo "STEP 1: Create Supabase Project"
echo "--------------------------------"
echo "1. Go to https://supabase.com"
echo "2. Sign up with email/password (FREE)"
echo "3. Create a new project:"
echo "   - Project Name: checkinpurple"
echo "   - Database Password: (choose secure password)"
echo "   - Region: (select closest to you)"
echo "4. Wait 2-3 minutes for project creation"
echo ""
echo "5. Get your credentials:"
echo "   - Go to Settings → API"
echo "   - Copy 'Project URL' → Save for VITE_SUPABASE_URL"
echo "   - Copy 'Anon public' key → Save for VITE_SUPABASE_ANON_KEY"
echo ""
echo "6. Create database tables:"
echo "   - Go to SQL Editor"
echo "   - Click 'New Query'"
echo "   - Copy and paste contents of database/schema.sql"
echo "   - Click 'Run'"
echo ""
echo "STEP 2: Create Agora Project"
echo "----------------------------"
echo "1. Go to https://console.agora.io"
echo "2. Sign up (FREE - 10,000 minutes/month)"
echo "3. Create a new project:"
echo "   - Project Name: checkinpurple"
echo "   - Use case: Interactive Live Streaming"
echo ""
echo "4. Get your credentials:"
echo "   - Go to Project Management"
echo "   - Click on your project"
echo "   - Copy 'App ID' → Save for AGORA_APP_ID"
echo "   - Click 'Generate' for Certificate → Save for AGORA_APP_CERTIFICATE"
echo ""
echo "STEP 3: Update .env.local"
echo "-------------------------"
echo "Create file: .env.local in project root with:"
echo ""
echo "VITE_SUPABASE_URL=paste_your_supabase_url"
echo "VITE_SUPABASE_ANON_KEY=paste_your_supabase_anon_key"
echo "AGORA_APP_ID=paste_your_agora_app_id"
echo "AGORA_APP_CERTIFICATE=paste_your_agora_app_certificate"
echo ""
echo "STEP 4: Test Setup"
echo "------------------"
echo "Run: pnpm dev"
echo "Open: http://localhost:8080"
echo ""
echo "Test checklist:"
echo "✓ Sign up as artist"
echo "✓ Click 'Go Live'"
echo "✓ See 'LIVE' badge"
echo "✓ Stream created in Supabase"
echo "✓ Real Agora token generated"
echo ""